#!/bin/sh
set -e
tar xvf torbutton-[% c('version') %].tar.[% c('compress_tar') %]
cd torbutton-[% c('version') %]
mkdir -p pkg
./makexpi.sh
mkdir pkg/tmp
cd pkg/tmp
unzip ../*.xpi
[% c('zip', {
	zip_src => '.',
	zip_args => dest_dir _ '/' _ c('var/dest_filename'),
	}) %]
