#!/bin/sh
set -e
rootdir=$(pwd)
mkdir -p dest/python
tar xvf [% c('input_files_by_name/python') %]
cd Python-[% c('version') %]
./configure
make -j$(nproc)
make prefix="$rootdir/dest/python" install
cd "$rootdir/dest"
[% c('tar', {
	tar_src => 'python',
	tar_args => '-cJf ' _ dest_dir _ '/' _ c('var/dest_filename'),
    }) %]
