#!/bin/bash
set -e
rootdir="$(pwd)"
instdir="$rootdir/inst/tor-browser_en-US"
mkdir -p "$instdir"

tar xvf [% project %]-[% c('version') %].tar.[% c('compress_tar') %]
cd [% project %]-[% c('version') %]
mv Bundle-Data/linux/Data "$instdir/Data"
cp RelativeLink/RelativeLink.sh "$instdir/start-tor-browser"

cd "$instdir"

tar xvf "$rootdir"/[% c('input_files_by_name/tor') %]
tar xvf "$rootdir"/[% c('input_files_by_name/tor-browser') %]

mkdir -p Data/Browser/profile.default/extensions/
mv "$rootdir"/[% c('input_files_by_name/torbutton') %] Data/Browser/profile.default/extensions/torbutton@torproject.org.xpi
mv "$rootdir"/[% c('input_files_by_name/tor-launcher') %] Data/Browser/profile.default/extensions/tor-launcher@torproject.org.xpi

httpseverywheredir='Data/Browser/profile.default/extensions/https-everywhere@eff.org'
mkdir -p "$httpseverywheredir"
pushd "$httpseverywheredir"
unzip "$rootdir"/[% c('input_files_by_name/https-everywhere') %]
popd

[% IF c('var/include_pt') %]
pushd "$instdir/Tor"
tar xvf "$rootdir"/[% c('input_files_by_name/pyptlib') %]
popd
[% END %]

cd ..
[% c('tar', {
	tar_src => [ 'tor-browser_en-US' ],
	tar_args => '-cJf ' _ dest_dir _ '/' _ c('var/dest_filename'),
    }) %]
